// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mcu_signals.proto
// Protobuf C++ Version: 7.36.0

#ifndef mcu_5fsignals_2eproto_2epb_2eh
#define mcu_5fsignals_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mcu_5fsignals_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_mcu_5fsignals_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_mcu_5fsignals_2eproto;
}  // extern "C"
namespace mcu {
class RawAdcSensor;
struct RawAdcSensorGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern RawAdcSensorGlobalsTypeInternal RawAdcSensor_globals_;
extern const ::google::protobuf::internal::ClassDataFull RawAdcSensor_class_data_;
#else
extern const RawAdcSensorGlobalsTypeInternal RawAdcSensor_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace mcu
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mcu {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED RawAdcSensor final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mcu.RawAdcSensor) */ {
  using Super_ = ::google::protobuf::Message;

 public:
  inline RawAdcSensor() : RawAdcSensor(nullptr) {}
  ~RawAdcSensor() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RawAdcSensor* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RawAdcSensor));
  }
#endif

  template <typename = void>
  explicit constexpr RawAdcSensor(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline RawAdcSensor(const RawAdcSensor& from) : RawAdcSensor(nullptr, from) {}
  inline RawAdcSensor(RawAdcSensor&& from) noexcept : RawAdcSensor(nullptr, ::std::move(from)) {}
  inline RawAdcSensor& operator=(const RawAdcSensor& from) {
    CopyFrom(from);
    return *this;
  }
  inline RawAdcSensor& operator=(RawAdcSensor&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const RawAdcSensor& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<RawAdcSensor>(&RawAdcSensor_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RawAdcSensor& a, RawAdcSensor& b) { a.Swap(&b); }
  inline void Swap(RawAdcSensor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RawAdcSensor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] RawAdcSensor* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<RawAdcSensor>(arena);
  }
  using Super_::CopyFrom;
  void CopyFrom(const RawAdcSensor& from);
  using Super_::MergeFrom;
  void MergeFrom(const RawAdcSensor& from) { RawAdcSensor::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RawAdcSensor* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "mcu.RawAdcSensor"; }

  explicit RawAdcSensor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RawAdcSensor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RawAdcSensor& from);
  RawAdcSensor(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RawAdcSensor&& from) noexcept
      : RawAdcSensor(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampNsFieldNumber = 1,
    kAdcValueFieldNumber = 2,
  };
  // uint64 timestamp_ns = 1;
  void clear_timestamp_ns() ;
  [[nodiscard]] ::uint64_t timestamp_ns() const;
  void set_timestamp_ns(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::uint64_t value);

  public:
  // uint32 adc_value = 2;
  void clear_adc_value() ;
  [[nodiscard]] ::uint32_t adc_value() const;
  void set_adc_value(::uint32_t value);

  private:
  ::uint32_t _internal_adc_value() const;
  void _internal_set_adc_value(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mcu.RawAdcSensor)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RawAdcSensor& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t timestamp_ns_;
    ::uint32_t adc_value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mcu_5fsignals_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RawAdcSensor

// uint64 timestamp_ns = 1;
inline void RawAdcSensor::clear_timestamp_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::uint64_t RawAdcSensor::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:mcu.RawAdcSensor.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void RawAdcSensor::set_timestamp_ns(::uint64_t value) {
  _internal_set_timestamp_ns(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:mcu.RawAdcSensor.timestamp_ns)
}
inline ::uint64_t RawAdcSensor::_internal_timestamp_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ns_;
}
inline void RawAdcSensor::_internal_set_timestamp_ns(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = value;
}

// uint32 adc_value = 2;
inline void RawAdcSensor::clear_adc_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adc_value_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::uint32_t RawAdcSensor::adc_value() const {
  // @@protoc_insertion_point(field_get:mcu.RawAdcSensor.adc_value)
  return _internal_adc_value();
}
inline void RawAdcSensor::set_adc_value(::uint32_t value) {
  _internal_set_adc_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:mcu.RawAdcSensor.adc_value)
}
inline ::uint32_t RawAdcSensor::_internal_adc_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.adc_value_;
}
inline void RawAdcSensor::_internal_set_adc_value(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adc_value_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace mcu


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // mcu_5fsignals_2eproto_2epb_2eh
