// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mcu_signals.proto
// Protobuf C++ Version: 7.36.0

#include "mcu_signals.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::mcu::RawAdcSensor
        {&::_pbi::kDescriptorMethods, &::descriptor_table_mcu_5fsignals_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace mcu {
class RawAdcSensor::_Internal {
 public:
  using HasBits = decltype(::std::declval<RawAdcSensor>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_._has_bits_);
};

constexpr RawAdcSensor::ParseTableT_ RawAdcSensor::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::mcu::RawAdcSensor>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // uint32 adc_value = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RawAdcSensor, _impl_.adc_value_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_.adc_value_)}},
      // uint64 timestamp_ns = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RawAdcSensor, _impl_.timestamp_ns_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_.timestamp_ns_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint64 timestamp_ns = 1;
      {PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_.timestamp_ns_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
      // uint32 adc_value = 2;
      {PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_.adc_value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr RawAdcSensor::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : timestamp_ns_{::uint64_t{0u}},
        adc_value_{0u} {}

template <typename>
constexpr RawAdcSensor::RawAdcSensor(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL RawAdcSensor::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RawAdcSensor(arena);
}
constexpr auto RawAdcSensor::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RawAdcSensor), alignof(RawAdcSensor));
}
constexpr auto RawAdcSensor::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &RawAdcSensor::MergeImpl,
          Super_::GetNewImpl<RawAdcSensor>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RawAdcSensor::SharedDtor,
          Super_::GetClearImpl<RawAdcSensor>(), &RawAdcSensor::ByteSizeLong,
              &RawAdcSensor::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_mcu_5fsignals_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct RawAdcSensorGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr RawAdcSensorGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 RawAdcSensor_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(RawAdcSensor::InternalGenerateClassData_(
            _default, &RawAdcSensor_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<RawAdcSensor>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~RawAdcSensorGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) RawAdcSensor _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<RawAdcSensor>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(RawAdcSensorGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST RawAdcSensorGlobalsTypeInternal RawAdcSensor_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* RawAdcSensor_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return RawAdcSensor_globals_.GetClassData();
#else
  return RawAdcSensor_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace mcu
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_mcu_5fsignals_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_mcu_5fsignals_2eproto = nullptr;
const ::uint32_t
    TableStruct_mcu_5fsignals_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::mcu::RawAdcSensor, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::mcu::RawAdcSensor, _impl_.timestamp_ns_),
        PROTOBUF_FIELD_OFFSET(::mcu::RawAdcSensor, _impl_.adc_value_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::mcu::RawAdcSensor)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::mcu::RawAdcSensor_globals_,
};
const char descriptor_table_protodef_mcu_5fsignals_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021mcu_signals.proto\022\003mcu\"7\n\014RawAdcSensor"
    "\022\024\n\014timestamp_ns\030\001 \001(\004\022\021\n\tadc_value\030\002 \001("
    "\rb\006proto3"
};
static ::absl::once_flag descriptor_table_mcu_5fsignals_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mcu_5fsignals_2eproto = {
    false,
    false,
    89,
    descriptor_table_protodef_mcu_5fsignals_2eproto,
    "mcu_signals.proto",
    &descriptor_table_mcu_5fsignals_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_message_globals,
    TableStruct_mcu_5fsignals_2eproto::offsets,
    file_level_enum_descriptors_mcu_5fsignals_2eproto,
    file_level_service_descriptors_mcu_5fsignals_2eproto,
};
namespace mcu {
// ===================================================================

RawAdcSensor::RawAdcSensor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, RawAdcSensor_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mcu.RawAdcSensor)
}
RawAdcSensor::RawAdcSensor(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RawAdcSensor& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, RawAdcSensor_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RawAdcSensor::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
     {}

inline void RawAdcSensor::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_ns_),
           0,
           offsetof(Impl_, adc_value_) -
               offsetof(Impl_, timestamp_ns_) +
               sizeof(Impl_::adc_value_));
}
RawAdcSensor::~RawAdcSensor() {
  // @@protoc_insertion_point(destructor:mcu.RawAdcSensor)
  SharedDtor(*this);
}
inline void RawAdcSensor::SharedDtor(MessageLite& self) {
  RawAdcSensor& this_ = static_cast<RawAdcSensor&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RawAdcSensor_class_data_ =
        RawAdcSensor::InternalGenerateClassData_(RawAdcSensor_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RawAdcSensor::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RawAdcSensor_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RawAdcSensor_class_data_.tc_table);
  return RawAdcSensor_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RawAdcSensor::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RawAdcSensor_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&RawAdcSensor_globals_));
  return RawAdcSensor_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const RawAdcSensor::ParseTableT_
    RawAdcSensor::_table_ =
        RawAdcSensor::InternalGenerateParseTable_(RawAdcSensor_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void RawAdcSensor::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:mcu.RawAdcSensor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&this_._impl_.timestamp_ns_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.adc_value_) -
                 reinterpret_cast<char*>(&this_._impl_.timestamp_ns_)) +
                 sizeof(_impl_.adc_value_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RawAdcSensor::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RawAdcSensor& this_ = static_cast<const RawAdcSensor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RawAdcSensor::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RawAdcSensor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mcu.RawAdcSensor)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 timestamp_ns = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_timestamp_ns() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_timestamp_ns(), target);
    }
  }

  // uint32 adc_value = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_adc_value() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_adc_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mcu.RawAdcSensor)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RawAdcSensor::ByteSizeLong(const MessageLite& base) {
  const RawAdcSensor& this_ = static_cast<const RawAdcSensor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RawAdcSensor::ByteSizeLong() const {
  const RawAdcSensor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mcu.RawAdcSensor)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // uint64 timestamp_ns = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_timestamp_ns() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp_ns());
      }
    }
    // uint32 adc_value = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_adc_value() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_adc_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RawAdcSensor::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<RawAdcSensor*>(&to_msg);
  auto& from = static_cast<const RawAdcSensor&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:mcu.RawAdcSensor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_timestamp_ns() != 0) {
        _this->_impl_.timestamp_ns_ = from._impl_.timestamp_ns_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_adc_value() != 0) {
        _this->_impl_.adc_value_ = from._impl_.adc_value_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RawAdcSensor::CopyFrom(const RawAdcSensor& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:mcu.RawAdcSensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RawAdcSensor::InternalSwap(RawAdcSensor* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_.adc_value_)
      + sizeof(RawAdcSensor::_impl_.adc_value_)
      - PROTOBUF_FIELD_OFFSET(RawAdcSensor, _impl_.timestamp_ns_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_ns_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_ns_));
}

::google::protobuf::Metadata RawAdcSensor::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace mcu
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_mcu_5fsignals_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
